### ISSUE TITLE
cannot build master

### ISSUE THREAD

**Issue by maxandersen** [jbee/purejin#174]
I do:

```
git clone https://github.com/jbee/purejin
cd purejin
jshell https://bit.ly/bach-main-build
```

with this java:
```
❯ jshell --version
jshell 16-ea
❯ java  --version
openjdk 16-ea 2021-03-16
OpenJDK Runtime Environment (build 16-ea+31-2150)
OpenJDK 64-Bit Server VM (build 16-ea+31-2150, mixed mode, sharing)
``` 

and I get:

```
.bach/build/module-info.java:1: error: package com.github.sormuras.bach.project does not exist
import com.github.sormuras.bach.project.Feature;
                                       ^
.bach/build/module-info.java:2: error: package com.github.sormuras.bach.project does not exist
import com.github.sormuras.bach.project.ProjectInfo;
                                       ^
.bach/build/module-info.java:3: error: package com.github.sormuras.bach.project.ProjectInfo does not exist
import com.github.sormuras.bach.project.ProjectInfo.Tweak;
                                                   ^
.bach/build/module-info.java:5: error: cannot find symbol
@ProjectInfo(
 ^
  symbol: class ProjectInfo
.bach/build/module-info.java:10: error: cannot find symbol
                Feature.GENERATE_API_DOCUMENTATION,
                ^
  symbol: variable Feature
.bach/build/module-info.java:11: error: cannot find symbol
                Feature.INCLUDE_SOURCES_IN_MODULAR_JAR
                ^
  symbol: variable Feature
.bach/build/module-info.java:14: error: cannot find symbol
                @Tweak(tool = "javac", with = {"-encoding", "UTF-8", "-g", "-parameters"}),
                 ^
  symbol: class Tweak
.bach/build/module-info.java:15: error: cannot find symbol
                @Tweak(tool = "javadoc",
                 ^
  symbol: class Tweak
.bach/build/module-info.java:33: error: cannot find symbol
                @Tweak(tool = "junit",
                 ^
  symbol: class Tweak
9 errors

Refresh failed: Non-zero exit code: 1

  Falling back to default Bach instance.

bach()
listExternalModules()
listMissingExternalModules()
listModulesWithRequiresDirectivesMatching(String)
listPublicStaticShellMethods()
listRecordings()
listSystemModules()
listToolProviders()
loadExternalModules(String...)
loadMissingExternalModules()
printModuleDescription(String)
printRecording(Recording)
refresh()
run(String,Object...)

.bach/build/module-info.java:1: error: package com.github.sormuras.bach.project does not exist
import com.github.sormuras.bach.project.Feature;
                                       ^
.bach/build/module-info.java:2: error: package com.github.sormuras.bach.project does not exist
import com.github.sormuras.bach.project.ProjectInfo;
                                       ^
.bach/build/module-info.java:3: error: package com.github.sormuras.bach.project.ProjectInfo does not exist
import com.github.sormuras.bach.project.ProjectInfo.Tweak;
                                                   ^
.bach/build/module-info.java:5: error: cannot find symbol
@ProjectInfo(
 ^
  symbol: class ProjectInfo
.bach/build/module-info.java:10: error: cannot find symbol
                Feature.GENERATE_API_DOCUMENTATION,
                ^
  symbol: variable Feature
.bach/build/module-info.java:11: error: cannot find symbol
                Feature.INCLUDE_SOURCES_IN_MODULAR_JAR
                ^
  symbol: variable Feature
.bach/build/module-info.java:14: error: cannot find symbol
                @Tweak(tool = "javac", with = {"-encoding", "UTF-8", "-g", "-parameters"}),
                 ^
  symbol: class Tweak
.bach/build/module-info.java:15: error: cannot find symbol
                @Tweak(tool = "javadoc",
                 ^
  symbol: class Tweak
.bach/build/module-info.java:33: error: cannot find symbol
                @Tweak(tool = "junit",
                 ^
  symbol: class Tweak
9 errors

Build error detected: Non-zero exit code: 1

java.lang.RuntimeException: Non-zero exit code: 1
	at com.github.sormuras.bach@17-ea+454f1ad/com.github.sormuras.bach.internal.ModuleLayerBuilder.build(ModuleLayerBuilder.java:43)
	at com.github.sormuras.bach@17-ea+454f1ad/com.github.sormuras.bach.internal.ModuleLayerBuilder.build(ModuleLayerBuilder.java:24)
	at com.github.sormuras.bach@17-ea+454f1ad/com.github.sormuras.bach.Bach.of(Bach.java:37)
	at com.github.sormuras.bach@17-ea+454f1ad/com.github.sormuras.bach.Main.run(Main.java:33)
	at REPL.$JShell$17.do_it$($JShell$17.java:6)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:209)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:116)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:119)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:144)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:262)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)
```

**Comment by jbee** [comment]
@sormuras you happy to look into it?

**Comment by sormuras** [comment]
Sure. It's due to a version mismatch - will update the README file, soon.

Should read: `jshell https://github.com/sormuras/bach/raw/releases/16/build`

@maxandersen - your local copy could be downgraded via:
```
bach init 16.0.1
bach clean
bach build
```
